name: Features

on:
  push:
    branches: [
      feature/*,
      fix/*
      hotfix/*
    ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ofn_vouchers_testing
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Cat .env
        run: cat .env
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress
      - name: Install Pint
        run: composer global require laravel/pint
      - name: Run Pint
        run: pint
      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Lint code"
      - name: Install NPM Dependencies
        run: npm install && npm run build
      - name: Generate application key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Install DB and migrate
        env:
          DB_DATABASE: ofn_vouchers_testing
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_PASSWORD:
        run: php artisan migrate:refresh
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: ofn_vouchers_testing
          DB_PASSWORD:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: php artisan test

